// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Express = require("bs-express/src/Express.js");
var Process = require("process");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var RouteAlertBehavior = require("route-alert-behavior/src/RouteAlertBehavior.bs.js");

var app = Express.express(/* () */0);

var router = Express.router(undefined, undefined, undefined, /* () */0);

Express.App.use(app, Express.Middleware.json(undefined, undefined, undefined, /* () */0));

Express.App.options(app, "/route_alerts", Express.Middleware.from((function (param, param$1, res) {
            Express.$$Response.setHeader("Access-Control-Allow-Origin", "*", res);
            Express.$$Response.setHeader("Access-Control-Allow-Headers", "*", res);
            return Express.$$Response.sendString("", res);
          })));

Express.App.post(app, "/route_alerts", Express.Middleware.from((function (_next, req, res) {
            Express.$$Response.setHeader("Access-Control-Allow-Origin", "*", res);
            console.log(Express.$$Request.bodyJSON(req));
            return Express.$$Response.sendJson(RouteAlertBehavior.createRouteAlertEffectHandler(Belt_Option.getExn(Express.$$Request.bodyJSON(req))), res);
          })));

Express.App.get(app, "/", Express.Middleware.from((function (_req, _next) {
            return (function (param) {
                return Express.$$Response.sendString("Hello, World!", param);
              });
          })));

function onListen(e) {
  var val;
  try {
    val = e;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      console.log(exn[1]);
      Process.exit(1);
      return /* () */0;
    } else {
      throw exn;
    }
  }
  console.log("Listening at http://127.0.0.1:3000");
  return /* () */0;
}

var server = Express.App.listen(app, 3000, onListen, /* () */0);

exports.app = app;
exports.router = router;
exports.onListen = onListen;
exports.server = server;
/* app Not a pure module */
